### ISSUE TITLE
Export Types setting not saved

### ISSUE THREAD

**Issue by elfren** [WilkoV/Fusion360_ExportIt#22]
Stl and step are always selected on startup even when f3d was previously selected and saved.

**Comment by WilkoV** [comment]
Never happend to me for dozens of designs. Can you export one of those designs and send me the log file of the export. For standard installations the log files are located under  

- %appdata%\Autodesk\Autodesk Fusion 360\API\AddIns\ExportIt\commands\logs (windows) or
- ~/Library/Application Support/Autodesk/Autodesk Fusion 360/API/AddIns/ExportIt/commands/logs (mac os).. 

Design-File would help also, because the exports do contain your changed ExportIt configuration (like in your first issue)

**Comment by elfren** [comment]
I should have said, the default settings when first opening a new file are for stl and step to be selected.  I would rather have the default to be step and f3d.  Is there a way to change the default?

When reopening a file, the settings were saved.

Is there also a way to have hidden bodies included by default?  Most of my files have hidden bodies, but I want to archive everything in the file as step files.

**Comment by WilkoV** [comment]
- You can edit the default with the Command Default Configuration (the orange icon)

![19-09-2020 23-19-10](https://user-images.githubusercontent.com/17180350/93689476-1b373a80-facf-11ea-9fc9-f853f83e8387.png)

- The add-in can't export hidden objects and has currently no function to unhide those bodies. I'm not sure if I want to implement this, because this would mean to actively change the design. I have a strong tendency to not do this.

**Comment by elfren** [comment]
It would be nice to have exporting hidden objects as an option, especially for archiving.
