### ISSUE TITLE
No active document found.

### ISSUE THREAD

**Issue by poudenes** [WilkoV/Fusion360_ExportIt#57]
Hi ALl,

nice tool.

When I open a design and change something and hit the export button I get the error:

"No active document found" 

Fusion 2.0.19983
MacOS 14.6.1

**Comment by WilkoV** [comment]
Hi @poudenes ,

can you please describe your workflow a bit more  detailed. I ask, because in some scenarios the export process creates a new (and unsaved) document. This is done because sometimes Fusion creates duplicate entries, the export has to regroup objects etc. The API doesn't allow me to close this temporary document. 

Regards Wilko

**Comment by poudenes** [comment]
I already found out the issue. I always save my project local to my iMac. I don't store them in the cloud.
Now I stored something in the cloud and it was working.

Would be create to export a project that's open in Fusion and export that one to different types.
So you can open a F3D file. Edit it and export it with the other extensions you like (STL, 3MF, STP, F3D)

**Comment by WilkoV** [comment]
I'm not sure if I can do this, because I store the export configuration in the Fusion document. This allows the user to export a design again and again with the same properties.  IIRC the API can only do this on saved documents. 
Your workflow is really an edge case, because Fusion is cloud based. But I check if I can make it work

**Comment by poudenes** [comment]
I appreciate your try to make this work. I was also search for a tool that can do this. Like most converter tools.
But there are none out there to do this task.

**Comment by poudenes** [comment]
Hey, 

Any news 😎

**Comment by WilkoV** [comment]
I tested several variants and not a single one had the functionality I wanted to keep .Since the CR is way outside the intended functionality of Fusion 360, I will reject this CR.
